wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: xgboost
    huggingface_version: 4.25.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.16
    start_time: 1670562587.140788
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 6
      - 11
      - 12
      - 49
      - 53
      - 55
      - 71
      3:
      - 13
      - 23
      4: 3.8.16
      5: 0.13.6
      6: 4.25.1
      8:
      - 5
